pinpt/go-common

- db/db.go
- db/db_test.go
From the driver docs.
"Usage of the charset parameter is discouraged because it issues additional queries to the server. Unless you need the fallback behavior, please use collation instead."
https://github.com/go-sql-driver/mysql
Switched collation from utf8_unicode_ci to utf8mb4_unicode_ci to compensate. utf8 is the alias to utf8mb3 and does not support 4 byte characters.
https://dev.mysql.com/doc/refman/5.5/en/charset-unicode.html
> Changed default collation and removed charset.

- io/io.go
- io/io_test.go
NewStream with gz would not close original file handle when Close is called. This leads to too many open files error if the reference to Writer is kept in memory. If the reference is not kept, the file would be closed when garbage collected, but the close return err would not be checked.
> io: fixed a bug where NewStream with gz would not close original file

- event/action/action.go
- It wasn't using the headers from the config
> Use config headers

- kafka/producer.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/DE-1352
adjusting kafka producer config based on issues seen in performance signals.
> DE-1352 kafka producer queue buffering adjustment

- upload/upload.go
this PR adds a new package for multi-part uploading to s3 via cloudfront.
we need to support both custom domains for s3 (via cloudfront) as well as we need safe and reliable multi-part uploads.  however, doing both on AWS at this moment is almost impossible.  so we are handling this ourselves.
here's how it works:
- the agent will get a URL via a normal agent.ExportRequest with the url as well as headers to set
- the event machine will generate the URL and the headers by using the cloudfront pre-signed cookies (vs the current one-time s3 presigned url). this is a different api but allows us to create a custom policy specific to the one time directory that allows the client to upload as many parts as needed using the same policy
- the uploader will upload the file in parts (by default …
> add uploader system

- datetime/time.go
- datetime/time_test.go
**Description:** fixed a bunch of compiler warnings  and added EpochMinuteApart which determines if two epoch dates are within a minute of eachother.
> add EpochMinuteApart⏰

- log/cobra.go
- log/log.go
- log/log_test.go
- Add ability to have a reasonable default (~10KB) max size of a message or any value when logging
- Add ability to control the max size via `--log-maxsize-value` when using the command logger
> log: add ability to truncate long values

- api/api.go
- event/event.go
Given the NLB issues we're having today, we have a bad AZ setup and every few requests are failing.  Because the default retry timeout is so low, we're timing out in the agent. These changes will allow the timeout to be tuned and extend the publish event to use 2m as a reasonable timeout.
- api: add method to override the default timeout NewHTTPAPIClientDefaultWithTimeout
- event: use NewHTTPAPIClientDefaultWithTimeout to customize the publish event to extend to 2m for sending to event-api
> fixes to extend timeout for sending events

- event/event.go
inside k8s using internal service url, dont do TLS verification because the cert is different
> TLS cert on k8s

- event/action/action.go
With this change, we can pass in more than one topic in the action.Register.
```
sub, err := action.Register(ctx, act, action.Config{
APIKey:  conf.APIKey,
GroupID: conf.GroupID,
Channel: conf.Channel,
Factory: factory,
Topics:  []string{ "topic_1", "topic_2", "topic_3"},
// Topic:  "topic_1", use either "Topic" for one or "Topics" for multiple
Errors:  errorsChan,
Offset:  "earliest",
})
```
> Allow more than one topic in action.Register

- kafka/consumer.go
- kafka/kakfa.go
- kafka: add support for managing your own offsets for a consumer
- kafka: add support for configuring the warn message on processing a message
> manage your own offsets

- eventing/eventing.go
- kafka/consumer.go
add topic partition to the actual TopicPartition so we can use it when more than 1 topic for a consumer
> add topic name to eventing.TopicPartition

- cmd/log.go
- improve parsing various different internal formats for level, timestamp etc
- improve parsing agent logs by handling comp -> pkg
- add support for filtering key/value with a special --include option
- add support for filtering on a message regular expression with --message option
you can run like this:
```
stern -n cloudagent ca -o raw | go-common log --log-level debug -i @module=jira-cloud
```
to get beautiful agent logs for the jira integration only
Filtering on a specific message (regexp):
```
stern -n cloudagent ca -o raw | go-common log --log-level debug  -m 'memory use'
```
> cmd: log improvements

- kafka/consumer.go
- kafka/kakfa.go
- if a panic duration is set on the config then the consumer will panic if it takes that duration or longer to commit a single message
> add panic duration to consumer🍔

- graphql/client.go
- graphql/client_test.go
- Ability to set graphql headers
- Override default golang user-agent headers so we know where we're making request from
> ability to override headers and use a specific header override for user-agent

- .gitignore
- Makefile
- event/action/action.go
- event/event.go
- filterexpr/filterexpr.go
- filterexpr/filterexpr_test.go
- filterexpr/grammar.peg
- json/jsonpath.go
- json/jsonpath_test.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/TIGR-79
Adds a filter expression engine with a custom parser grammar using PEG.
Allows us to build filters from maps similar to a very very simplified lucene syntax.
For example, we can match:
```
a: "b"
```
And that will match the following example expression:
```json
{
"a": "b"
}
```
You can also use conjunctions like:
```
a: "b" OR a: "c"
```
> TIGR-79 add filter expression engine

- log/cobra.go
Allows setting default log-level for command logger. So that I don't have to add the flag every time I'm piping logs into `go-common log`.
```bash
go-common log --log-level debug
```
becomes:
```bash
go-common log
```
it'll still use whatever flag you give it though so if someone sets it to `error`, this shouldn't break any scripts since we're usually explicit
> allow changing default log level ✏️

- strings/strutil.go
I wrote this function in my very early days. There is no need to check for `HasSuffix` and `HasPrefix` since the Trim functions already check for that
> simplify join url

- fileutil/file.go
- fileutil/file_test.go
- hash/hash.go
- hash/hash_test.go
- So I accidentally copied *2* checksum methods into 2 different modules in go-common. the one in fileutil was a better implementation so stole the meat of that and put it into hash as `ChecksumFrom` which will let us take checksums of stuff we already have in memory without loading the thing in memory again (yay!) and then used it in fileutil. I just used `sha256` cause thats what we use for generating all our certs/keys. If we want to use `sha512`  for checksums of files instead we should do it now.
> fix double checksum 🤦‍♀️

- hash/hash.go
- hash/hash_test.go
adds `ChecksumCopy` which will do the same as io.Copy, but also returns a sha256 checksum for the data copied
> add checksum copy©

- event/event.go
My guess is that this policy https://github.com/pinpt/event-api/blob/master/pkg/server/consume.go#L270 is causing this panic in the agents, which is causing long historicals to start over.
```
panic: websocket: close 1008 (policy violation): timed out
goroutine 163 [running]:
```
> reconnect after policy violation

- event/event.go
- event/event_test.go
Signed-off-by: Andrew Kunzel <akunzel@pinpoint.com>
**JIRA:** https://pinpt-hq.atlassian.net/browse/BOLT-186
This moves the Queue name generation from event-api repo to go-common. A follow up
> BOLT-186: Moving GenerateQueueName method to go-common

- filterexpr/filterexpr_test.go
- filterexpr/grammar.go
- filterexpr/grammar.peg
right now you have to have a key that is explicitly null.
in a lot of our serialization we remove keys that have null value from JSON which means it won't match for this case.
This change fixes that
> a null filter should also missing a missing key

- filterexpr/filterexpr_test.go
- filterexpr/grammar.go
- filterexpr/grammar.peg
**JIRA:** https://pinpt-hq.atlassian.net/browse/GOLD-300
Add support for matching a filter expression against JSON encoded as a string (such as we do in db change)
So let's say you have this normal db change type object:
```json
{
"action": "UPSERT",
"change_date": {
"epoch": 1600183776694,
"offset": 0,
"rfc3339": "2020-09-15T15:29:36.694+00:00"
},
"customer_id": "a8a78d9c16839b97",
"data": "{\"_id\":\"088700e68ca935c2\",\"active\":false,\"attendee_ids\":[\"ff1f0458cfe3e85d\",\"579dc0e39f8f8bf8\"],\"attendee_ref_id\":\"\",\"busy\":false,\"calendar_id\":\"\",\"created_ts\":1600183776664,\"customer_id\":\"a8a78d9c16839b97\",\"description\":\"\",\"end_date\":{\"epoch\":1600182000000,\"offset\":-300,\"rfc3339\":\"2020-09-15T10:00:00-05:00\"},\"integration_instance_id\":\"fa191 …
```
> add support for decoding json strings for filter expression

- httpmessage/http.go
As per their [docs](https://golang.org/src/net/http/server.go?s=3003:5866#L85):
`Changing the header map after a call to WriteHeader (or Write) has no effect unless the modified headers are trailers.`
so `Cache-Control` and `Content-Type` are never set
> WriteHeader is to be called _after_ all headers are set

- rabbitmq/rabbitmq.go
This was the only other change that went out this afternoon, so either there's a consumer leak that sprung up again, or the nowait bit is not working as expected and keeping consumers around after they should be cancelled.
> move back to no-wait true when cancelling a subscription; don't need to wait since it's an ackable queue

- event/event.go
- event/event_test.go
- rabbitmqsmartshovel/rabbitmqsmartshovel.go
Adds an additional implementation of the rabbitmq session for a smartshovel.
This adds the necessary logic to publish to the EventApi-output exchange or the Ingest Exchange depending if the session is a shovel or not.
Since the smartshovel uses a direct exchange instead of topic binding, it made sense to keep around the topic exchange session that we had in case we need to rollback and keep using it. (Or if other things we use need a topic-based session, it works!)
> NAN-543: smartshovel addition to rabbitmq common code

- go.mod
- go.sum
- metrics/metrics.go
- metrics/server.go
Add a metric server, metrics and a PPROF server to go common.
This should help keep metrics uniform throughout the golang stack for services that do not operate over HTTP
> Shared metrics
