pinpt/go-common

- Gopkg.lock
- datetime/time.go
- datetime/time_test.go
- db/db_test.go
- Condition change to know if the date come using the layout `2006-01-02T15:04:05.999999999-07:00`
> Date improvement

- agent/event.go
- agent/event_test.go
- api/api.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/BE-1397
-  Added methods to get csrf token and post events
> BE-1397  Added methods to get csrf token and post events

- json/object.go
- json/object_test.go
**Description:** create object needed to stop looking for values after it has found one that matched it's map
> fixed create object 🧰

- datamodel/datamodel.go
- event/action/action_test.go
- event/event_test.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/BE-1409
> BE-1409 adding GetStateKey to model

- json/object.go
- json/object_test.go
stream to map was only returning the first result. 
kept optimization for `$.id` and also added tests✅
> fixed stream to map so that it returns more than one result

- datamodel/datamodel.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/DE-1442
> DE-1442 add ttl to model topic config

- datetime/time.go
- datetime/time_test.go
**Description:** need to parse empty string as zero time
> allow empty times in datetime⏰

- json/jsonpath.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/DE-1462
**Description:** 'string' action is returning a value of "<nil>" on null data.
> DE-1462: 'string' action to handle nil values

- event/event.go
- it wasn't resubscribing after the idle time
> it wasn't resubscribing after the idle time

- log/log.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/DE-1499
Fix data changes for slices and maps.
When a slice/map was sent as a value to the logger and the value was masked, the original value also changed.
> DE-1499: Fix log data mutations

- hash/hash.go
- hash/hash_test.go
> fixed hash func from panicing on nil type😱

- kafka/consumer.go
Check if the message is json or avro
> Fixed encoding

- datetime/time.go
- io/io.go
moving generic time functions from pipeline
also adding implementation of  ReaderCloser here
> extracting common code from pipeline

- datamodel/datamodel.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/BE-1657
**Description:** need to be able to get the stream name on a generic model
> DE-1657 added getstreamname to model interface🙎‍♀️

- api/api.go
- event/event.go
allow for service to service communication within k8 cluster
> k8 communication

- .gitignore
- log/log.go
* changed the msgKey to match how the typescript services are logging.
* added my .idea dir to gitignroe
https://pinpt-hq.atlassian.net/browse/PLAT-152
> Changed the logging message key

- upload/upload.go
- upload/upload_test.go
added test cases (will write some more)
> fix issue with 0 byte uploads

- event/event.go
- event: fixed deadlock when a subscriber disconnects from the server and attempts to reconnect and hangs on sending ready message 
- event: fixed issue where the publish fails when the event-api isn't available
> event fixes

- event/event.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/DE-1904
Add support for turning off TLS cert verification when running inside docker talking back to the local machine.
> add support for using docker internal hostname inside kubernetes

- graphql/client.go
- graphql/client_test.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/AGT-61
> AGT-61 Added graphql http client

- cmd/log.go
pipe your json into the log command!
```
echo '{"level":"info","message":"hello!"}' | go-common log
```
> add the log command 💎

- event/event.go
- event: handle connection reset by peer error and io timeout error (retry)
- event: reused insecure http/ws connection
- event: support gzip encoding
- event: handle timeout on close
- event: add support for dispatch timeout
> event: improve event package

- cmd/log.go
**Description:** lets us log to different levels, among other things
> use register flags for rich logger experience 💵

- event/event.go
- dont start ping timer until after subscription is started
- also call the original ping handler as well
> call original ping handler🤚

- event/action/action.go
- event/event.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/PLAT-297
add temporary flag which will allow the queue to be delete if not used
> PLAT-297 - indicate if the subscription is temporary

- event/event.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/DE-2164
On  read from websocket, need to use `IsErrorRetryable` method and also added broken pipe to whitelist of retryable errors.
> retry on any broken pipe which indicates a remote closed connection

- event/event.go
- if the connection never happens then this is nil and panics on shutdown
> fix panic on shutdown before connection established🛠

- filterexpr/filterexpr_test.go
- filterexpr/grammar.peg
> allow spaces in regexp

- filterexpr/filterexpr_test.go
- filterexpr/grammar.go
- filterexpr/grammar.peg
add support for underscores and dashes in keys and update test cases
> add support for underscore and dash in key name

- event/event.go
add support for publishing on an event.SubscriptionChannel in addition to over HTTP
> event: add websocket subscription channel publish support

- event/event.go
we need this when the channel is in commit mode and the commit takes longer than 30s so the channel cannot receive a ping while blocking for the commit
> ability to disable pings on subscription channel. 

- event/action/action.go
- consolidates the event.Subscription and the action.Config objects (so they're easier to keep in sync)
> pushes DisablePing into the event action wrapper

- event/action/action.go
> remove extra import

- filterexpr/filterexpr.go
- filterexpr/filterexpr_test.go
> increase default filter expression length and updated test case

- fileutil/file.go
- fileutil/file_test.go
Co-authored-by: Jeff Haynie <jhaynie@pinpoint.com>
- adds handy zip function
- adds handy checksum functions
> Add zip/checksum functions to fileutil

- fileutil/file.go
- hash/hash.go
- hash/hash_test.go
- adds checksum method for sha256 checksum of files
- adds safe unzip
> Add Checksum to hash

- api/api.go
- api/api_test.go
- hash/hash.go
- hash/hash_test.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/GOLD-106
- adds a test case to checksum that I had locally and forgot to check in
- adds app service to api. 
I dont know how I would make it work for `dev` with url `https://app.edge.ppoint.io:3001/`. Should I add a `dev-edge` channel?
> GOLD-106 add app service

- event/event.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/PROD-740
Remove the ping code
> remove ping code

- filterexpr/filterexpr.go
- filterexpr/filterexpr_test.go
- filterexpr/grammar.go
- filterexpr/grammar.peg
**JIRA:** https://pinpt-hq.atlassian.net/browse/GOLD-117
Fixed ability to do multiple groupings
> fix ability to use multiple groupings

- datamodel/datamodel.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/GOLD-30
> GOLD-30 add partial model interface😀

- datetime/time.go
- datetime/time_test.go
this was preventing me from pretty one-liners✨
> remove impossible error from NewDateWithTime⏰

- filterexpr/filterexpr_test.go
- filterexpr/grammar.go
- filterexpr/grammar.peg
**JIRA:** https://pinpt-hq.atlassian.net/browse/GOLD-216
> add support for null in expression to represent missing a value or null

- event/event.go
We are getting panic on trying to commit a message sometimes.  It seems to be when we're closing a socket.
This will error instead of panic and will ignore pipe broken messages when we're closed.
> dont crash when we get a broken pipe trying to send commit/nack

- filterexpr/filterexpr_test.go
- filterexpr/grammar.go
- filterexpr/grammar.peg
**JIRA:** https://pinpt-hq.atlassian.net/browse/GOLD-300
> add support for matching a filter expression inside a string array or interface like string

- event/event.go
From Publish, I keep getting back a non-nil error with an empty string body. This should clear that up
> Have an explicit error message on publish endpoint😤

- datetime/time.go
- datetime/time_test.go
Because of how numbers work we can get the timezone without a possible error! Wild!
> Add TimeFromDate ⏰📅

- event/event.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/GOLD-419
This Error should be retry-able in most scenarios 🤔
> GOLD-419 Add TLS handshake timeout as a retryable error🤝

- auth/auth.go
- auth/auth_test.go
- go.sum
**JIRA:** https://pinpt-hq.atlassian.net/browse/NAN-525
Add url safe version of encrypt/decrypt
> add a url safe version of encrypt and decrypt string

- rabbitmq/channelhost.go
- rabbitmq/connectionhost.go
- rabbitmq/connectionpool.go
- rabbitmq/rabbitmq.go
> add rabbitmq stuff so we can use  in pipeline

- api/api.go
- api/api_test.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/GOLD-400
- adds the webhook service
> GOLD-400 Add webhook service to backend url

- rabbitmq/connectionpool.go
- rabbitmq/rabbitmq.go
> Fix log messages, Change QoS

- rabbitmq/rabbitmq.go
- rabbitmqsmartshovel/rabbitmqsmartshovel.go
> fix blocking channel when shutting down a publish-only session

- go.mod
- go.sum
- slack/slack.go
**JIRA:** https://pinpt-hq.atlassian.net/browse/GOLD-480
> added slack client

- metrics/metrics.go
forgot to register the websocket metric
> register websocket metric

- .gitignore
- cmd/auth.go
these are pretty handy.
```
❯ go-common encrypt "hello world" password
svgb8aBD2hUvrFJvxZFAR9y+Y5XNnqGNFXM772gfVzmDmOr8yTDhd1bvWjGOQbdg4fIleWi/DQ==
❯ go-common decrypt svgb8aBD2hUvrFJvxZFAR9y+Y5XNnqGNFXM772gfVzmDmOr8yTDhd1bvWjGOQbdg4fIleWi/DQ== password
hello world
```
> Add encrypt and decrypt commands 🔐

- metrics/metrics.go
> add missing bits to the metrics to consolidate them with istio

- auth/auth.go
Adds `GetAuthInfo` which properly decodes auth headers into a nice object. Need to figure out internal auth though.
> Implement a generic internal auth
